/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.vaporware.com.user_interface;

import jade.core.Profile;
import jade.core.ProfileImpl;
import jade.wrapper.AgentController;
import jade.wrapper.StaleProxyException;
import org.vaporware.com.domain.Communicator;

/**
 *
 * @author pacog
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
                 
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Falltube\n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }                    
    private static jade.wrapper.AgentContainer mainContainer;
    private static int port;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws StaleProxyException {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
       
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
        Communicator c1=new Communicator(jTextArea1);
         port = 4552;
        // Llamamos a la runtime de JADE
        jade.core.Runtime rt = jade.core.Runtime.instance();

        // Salimos de la JVM cuando no hay mas containers
        rt.setCloseVM(true);
        System.out.print("<Runtime Creado>\n");

        // Creamos un perfil por defecto
        Profile profile = new ProfileImpl(null, port, null);
        System.out.print("<Perfil Creado>\n");

        System.out.println("<Lanzando Plataforma>" + profile);
        mainContainer = rt.createMainContainer(profile);

        // Ponemos un perfil por defecto y creamos un container
        ProfileImpl pContainer = new ProfileImpl(null, port, null);
        System.out.println("<Lanzando Containers>" + pContainer);

        jade.wrapper.AgentContainer cont = rt.createAgentContainer(pContainer);
        System.out.println("<Containers Creados>");

        System.out.println("<Lanzando el agente en el container principal>");

        AgentController rma = mainContainer.createNewAgent("Ag1",
                "org.vaporware.com.domain.DownloaderAgent", new Object[0]);
        rma.start();
        
    }

                  
    private static javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea jTextArea1;
             
}
